apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infisical.kubeSecretRef }}
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  REDIS_URL: {{ .Values.redis.connectionUri | quote }}
  SITE_URL: {{ .Values.siteUrl | default (printf "https://%s" .Values.ingress.hostName) | quote }}
  DB_CONNECTION_URI: {{ .Values.postgresql.useExistingPostgresSecret.connectionUri | quote }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_FROM_ADDRESS: {{ .Values.smtp.fromAddress | quote }}
  SMTP_FROM_NAME: {{ .Values.smtp.fromName | quote }}
  CLIENT_ID_GOOGLE_LOGIN: {{ .Values.auth.google.clientId | quote }}
  CLIENT_SECRET_GOOGLE_LOGIN: {{ .Values.auth.google.clientSecret | quote }}
  CLIENT_ID_GITHUB_LOGIN: {{ .Values.auth.github.clientId | quote }}
  CLIENT_SECRET_GITHUB_LOGIN: {{ .Values.auth.github.clientSecret | quote }}
